"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-07 15:50:05.314717
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=False),
    sa.Column('text_prompt', sa.String(length=500), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_classes_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classes')),
    sa.UniqueConstraint('project_id', 'name', name=op.f('uq_classes_project_id'))
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_project_id'), ['project_id'], unique=False)

    op.create_table('dataset_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_dataset_versions_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_versions'))
    )
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_versions_project_id'), ['project_id'], unique=False)

    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('thumb_key', sa.String(length=500), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_images_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images')),
    sa.UniqueConstraint('project_id', 'sha256', name=op.f('uq_images_project_id'))
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_images_project_status', ['project_id', 'status'], unique=False)

    op.create_table('labeling_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('target', sa.String(length=16), nullable=False),
    sa.Column('image_ids', sa.JSON(), nullable=True),
    sa.Column('include_reviewed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_labeling_jobs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labeling_jobs'))
    )
    with op.batch_alter_table('labeling_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labeling_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_labeling_jobs_status'), ['status'], unique=False)

    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('x_min', sa.Float(), nullable=False),
    sa.Column('y_min', sa.Float(), nullable=False),
    sa.Column('x_max', sa.Float(), nullable=False),
    sa.Column('y_max', sa.Float(), nullable=False),
    sa.Column('shape_type', sa.String(length=16), nullable=False),
    sa.Column('points', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_annotations_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_annotations_image_id_images'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['labeling_jobs.id'], name=op.f('fk_annotations_job_id_labeling_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_annotations'))
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotations_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_image_id'), ['image_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_source'), ['source'], unique=False)

    op.create_table('labeling_job_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('num_detections', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_labeling_job_items_image_id_images'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['labeling_jobs.id'], name=op.f('fk_labeling_job_items_job_id_labeling_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labeling_job_items'))
    )
    with op.batch_alter_table('labeling_job_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labeling_job_items_job_id'), ['job_id'], unique=False)

    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('framework', sa.String(length=64), nullable=False),
    sa.Column('weights_key', sa.String(length=500), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f('fk_models_dataset_version_id_dataset_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_models_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_models_project_id'), ['project_id'], unique=False)

    op.create_table('class_exemplars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('source_image_id', sa.Integer(), nullable=True),
    sa.Column('source_annotation_id', sa.Integer(), nullable=True),
    sa.Column('x_min', sa.Float(), nullable=False),
    sa.Column('y_min', sa.Float(), nullable=False),
    sa.Column('x_max', sa.Float(), nullable=False),
    sa.Column('y_max', sa.Float(), nullable=False),
    sa.Column('crop_storage_key', sa.String(length=500), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_class_exemplars_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_annotation_id'], ['annotations.id'], name=op.f('fk_class_exemplars_source_annotation_id_annotations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_image_id'], ['images.id'], name=op.f('fk_class_exemplars_source_image_id_images'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_exemplars'))
    )
    with op.batch_alter_table('class_exemplars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_exemplars_class_id'), ['class_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_exemplars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_exemplars_class_id'))

    op.drop_table('class_exemplars')
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_models_project_id'))

    op.drop_table('models')
    with op.batch_alter_table('labeling_job_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labeling_job_items_job_id'))

    op.drop_table('labeling_job_items')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotations_source'))
        batch_op.drop_index(batch_op.f('ix_annotations_image_id'))
        batch_op.drop_index(batch_op.f('ix_annotations_class_id'))

    op.drop_table('annotations')
    with op.batch_alter_table('labeling_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labeling_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_labeling_jobs_project_id'))

    op.drop_table('labeling_jobs')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index('ix_images_project_status')
        batch_op.drop_index(batch_op.f('ix_images_project_id'))

    op.drop_table('images')
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_versions_project_id'))

    op.drop_table('dataset_versions')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_project_id'))

    op.drop_table('classes')
    op.drop_table('projects')
    # ### end Alembic commands ###
