"""review audits

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-09 14:36:37.283419
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_review_audits_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_audits'))
    )
    with op.batch_alter_table('review_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_audits_project_id'), ['project_id'], unique=False)

    op.create_table('review_audit_items',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['review_audits.id'], name=op.f('fk_review_audit_items_audit_id_review_audits'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_review_audit_items_image_id_images'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audit_id', 'image_id', name=op.f('pk_review_audit_items'))
    )
    with op.batch_alter_table('review_audit_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_audit_items_image_id'), ['image_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_audit_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_audit_items_image_id'))

    op.drop_table('review_audit_items')
    with op.batch_alter_table('review_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_audits_project_id'))

    op.drop_table('review_audits')
    # ### end Alembic commands ###
